# Generated by Django 5.1.3 on 2024-11-17 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_surname', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image/Doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_surname', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('appointments_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctors')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patientdetails')),
            ],
        ),
    ]
